### ISSUE TITLE
Overriding implementation of existing commands

### ISSUE THREAD

**Issue by Thodor12** [TheNexusAvenger/Nexus-Admin#1]
I looked at the implementation of the Registry and by the looks of it if you define a command with the same name as an existing command they will both be kept in the CommandsByGroup table [(source).](https://github.com/TheNexusAvenger/Nexus-Admin/blob/master/src/Common/Registry.lua#L130) Does Nexus run both implementations, only the native implementation or only the new implementation?

**Comment by TheNexusAvenger** [comment]
This is definitely a design flaw and can be addressed in the planned 2.0.1 release, although very minor because of how it is. Nexus Admin itself doesn't run the commands; Cmdr does. Anything registered to Nexus Admin is just passed through to Cmdr's registry to allow it to execute commands, with `CommandsByGroup` used for storing commands to be referenced by the `cmds` command. `CommandsByGroup` is not a source of truth of the registered commands and has no effect on executing.

While it is an internal value, there could be some unwanted consequences for replacing commands when viewing them with `cmds`. I will leave this issue open until it is fixed. Might be a few months since I am waiting for `ReplicatedScriptService` to be enabled. If you are trying to use `CommandsByGroup` for any reason, or anything not covered in the docs, you should consider creating a feature request for an officially support API.

**Comment by Thodor12** [comment]
I did give it an actual test to see if it works and by the looks of it, it might be handled by Cmdr but I couldn't find a confirmation to it in the source of Cmdr itself. It seems to only run the implementation that was last created by the registry.

First I just assigned some modules below the loader and it only used those overridden commands.
Then I used a custom loader to test what would happen if I first included the custom commands first and then load the included commands and then only the original command was used.

So I think it is safe to say that overriding commands works as long as you define them after the included commands. Might be useful to note that down in the creating commands section of the gh-pages. Can provide a pull if wanted.

**Comment by TheNexusAvenger** [comment]
> I did give it an actual test to see if it works and by the looks of it, it might be handled by Cmdr but I couldn't find a confirmation to it in the source of Cmdr itself. It seems to only run the implementation that was last created by the registry.

See: https://github.com/evaera/Cmdr/blob/master/Cmdr/Shared/Registry.lua#L118

> So I think it is safe to say that overriding commands works as long as you define them after the included commands.

Is there a condition you see where you can load the included commands _after_ custom commands? With the included loader, it should load everything, including the included commands, and then require any `ModuleScript`s parented to the loader script.

**Comment by Thodor12** [comment]
> Is there a condition you see where you can load the included commands after custom commands? With the included loader, it should load everything, including the included commands, and then require any ModuleScripts parented to the loader script.

In almost every situation no unless they would be using the custom loader and implemented it in a strange manner. I was just experimenting as to how it worked precisely but https://github.com/evaera/Cmdr/blob/master/Cmdr/Shared/Registry.lua#L118 confirmed it.
